name: Build Docker Image for Spring Boot App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Add Sensitive.Properties
        run: echo "${{ secrets.PROPERTIES }}" > src/main/resources/sensitive.properties

      - name: Maven Clean
        run: ./mvnw clean

      - name: Maven install
        run: ./mvnw install -DskipTests

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and Push Image
        run: |
          docker buildx build -rm --platform linux/amd64 \
          --file Dockerfile \
          -t tevindeale/rocketbank-spring-api:latest \
          --push .